services:
  db:
    image: postgres:18.0
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/:ro